---


#ensure that we have the directorys that we need
- name: kibana-install | Ensure kibana plugin directories exists
  file:
    path="{{ item }}"
    state=directory
    recurse=yes
  with_items:
     - "{{elasticsearch_config_dir}}/kibana/"

# if elasticsearch is not already deployed
# copy esticserach from elasticsearch_base_dir to elasticsearch_deploy_dir
- name: kibana install | config kibana.yml
  template:
#    src=../templates/elasticsearch.yml.j2
    src=../templates/kibana.yml.j2
    dest="{{elasticsearch_config_dir}}/kibana/kibana.yml"