---
# Elasticsearch Ansible Tasks

# Install Java
#- include: java.yml
#  when: elasticsearch_install_java

# Configure timezome
#- include: timezone.yml

# Install and configure elasticsearch
- include: configure-elasticsearch.yml

# install elasticserach kibana
- include: start-elasticsearch.yml
  when: (start_elastic_search is defined)
#


