---

#check to see if elasticsearch is already running
  - name: Start elasticsearch | Check if elasticsearch is already running
    stat:
      path={{elasticsearch_pid_dir}}/{{dev_pid}}
    register: elasticsearch_running

#start elastic search when it's not already running
  - name: Start elasticsearch | Staring elasticsearch
    shell: "{{elasticsearch_executable_dir}}/./elasticsearch -d -p  {{elasticsearch_pid_dir}}/{{elasticsearch_node_name}} --path.conf={{elasticsearch_config_dir}}"
    when: elasticsearch_running.stat.exists == False