---

#check to see if elasticsearch is already running
  - name: Start kibana | Check if kibana is already running
    stat:
      path={{ elasticsearch_pid_dir }}/kibana_pid_{{elasticsearch_node_name}}
    register: kibana_running

#start elastic search when it's not already running
  - name: Start kibana | Staring kibana
    shell: "{{kibana_dir}}/bin/./kibana -d -p  {{ elasticsearch_pid_dir }}/kibana_pid_{{elasticsearch_node_name}} --config {{elasticsearch_config_dir}}"
    when: kibana_running.stat.exists == False
    ignore_errors: false