---

#check to see if elasticsearch is already running
  - name: Start elasticsearch | Check if elasticsearch is already running
    stat: path={{elasticsearch_pid_dir}}/{{elasticsearch_node_name}}
    register: elasticsearch_running

#start elastic search when it's not already running
  - name: Start elasticsearch | Staring elasticsearch
    shell: "{{elasticsearch_executable_dir}}/./elasticsearch -d -p  {{elasticsearch_pid_dir}}/{{elasticsearch_node_name}} --path.conf={{elasticsearch_config_dir}}"
    when: elasticsearch_running.stat.exists == False
    register: command_result
    failed_when: "'Exception' in command_result.stderr"
    ignore_errors: false

# Wait for Elasticsearch node to come back into cluster
  - name: wait for the elastic node to start
    shell: curl -XGET http://localhost:9200/_nodes/{{elasticsearch_node_name}}/info
    register: result
    until: result.stdout.find("my-es-node-1") != -1
    retries: 200
    delay: 3
    ignore_errors: false
