---
# Elasticsearch Ansible Variables

#elasticsearch_user: my-elasticsearch
#elasticsearch_group: my-elasticsearch
elasticsearch_download_url: https://download.elasticsearch.org/elasticsearch/elasticsearch
elasticsearch_version: elasticsearch-2.3.3
elasticsearch_apt_repos:
  - 'ppa:webupd8team/java'
elasticsearch_apt_java_package: oracle-java7-installer
elasticsearch_apt_dependencies:
  - htop
  - ntp
  - unzip
elasticsearch_max_open_files: 65535
elasticsearch_base_dir: /Users/Munish/Development/dev/{{elasticsearch_version}}
elasticsearch_deploy_dir: /Users/Munish/Development/dev/#deploy
elasticsearch_plugin_dir: "{{elasticsearch_base_dir}}/{{elasticsearch_version}}/plugins"
elasticsearch_log_dir: "{{elasticsearch_deploy_dir}}/{{elasticsearch_version}}/logs"
elasticsearch_data_dir: "{{elasticsearch_deploy_dir}}/{{elasticsearch_version}}/data"
elasticsearch_config_dir: "{{elasticsearch_deploy_dir}}/{{elasticsearch_version}}/config"

elasticsearch_work_dir: /tmp/elasticsearch
elasticsearch_pid_dir: "{{elasticsearch_deploy_dir}}/{{elasticsearch_version}}/pid"

elasticsearch_service_startonboot: no
elasticsearch_timezone: "Etc/UTC"  # Default to UTC

#elasticsearch_http_cors_enabled: "false"
elasticsearch_service_state: started

# Non-Elasticsearch Defaults
apt_cache_valid_time: 300 # seconds between "apt-get update" calls.
elasticsearch_install_java: "true"

start_elastic_search: "true"
#stop_elastic_search: "true"

#elastic pid used to
dev_pid: devPid